### ISSUE TITLE
How to detect if a project is a Deno project

### ISSUE THREAD

**Issue by axetroy** [axetroy/vscode-deno#11]
There doesn't seem to be an effective way to detect if a project is a Deno project

Here are a few options

### 1. Match for `import xxx from "https://xxxx"`
> we can be matched by regular expression/string.
> 
> If it meets the above style, then it is considered a Deno project

### 2. Analyze API calling with AST

> Analysis via Typescript's AST
> 
> If there are some API calls like `Deno.cwd()` / `Deno.open()` and other Deno APIs
> 
> then it is considered a Deno project

These methods can detect

But I don't think this is a good approach and It will cost performance.

If you have a better idea

please let me know

**Comment by Soremwar** [comment]
Shouldn't really be much of a struggle. In theory any JS or TS script is potentially a Deno project (In fact I use it to test Deno and work in a laravel project with little to no hassle).

The extension could however require a configuration file generated by VS Code that specifies the entry point (main file) for the app, import map, etc.

That way you might even be able to port Deno commands such as bundle or fmt since you know the specifications for the app and can wrap this commands as VS utilities for use ease.

**Comment by brandonkal** [comment]
Browsers can understand url imports as well. Though it is reasonable to use the Deno runtime to provide dev tooling for such projects. You could just run a Regex for `(https:\/\/deno\.land|Deno)`. I still prefer explicitness, but the extension could prompt to set "deno.enable" if it is unset.

**Comment by axetroy** [comment]
Thanks for your feedback

I thought about it a bit more, and I found it unnecessary to check whether the project is a Deno project

Users need to specify the configuration themselves

```json
// .vscode/setting.json
{
  "deno.enable": true
}
```

I think this is a better way
