### ISSUE TITLE
Why the fork?

### ISSUE THREAD

**Issue by TranquilMarmot** [axetroy/vscode-deno#14]
I'm just wondering _why_ this version was forked from https://github.com/justjavac/vscode-deno when that repo still seems active? There was a commit and a release < 3 months ago. Has @justjavac abandoned the project?

It's really confusing to see two extensions in the VSCode marketplace with the same name and such similar details! It would be nice to standardize on one and remove the other. I would love to see this moved to https://github.com/denoland but I'm not sure how @ry feels about that.

**Comment by axetroy** [comment]
Actually, `justjavac/vscode-deno` is still under maintenance

And I am also one of the maintainers.

### Why fork

It's because @justjavac has been too busy lately to review PRs and updates

And I also have some ideas I need to implement (E.g. `release in CI` / `Simplified extension` and more)

I think it would be more appropriate to release a new version myself

### there are several Deno extensions on the vscode market

That shows that it is a good thing, everyone started to pay attention to Deno

But I don't think it's necessary to move it to the official repo.

### At first I wanted to migrate it to `denolib/vscode-deno` and maintain it with the denolib members

But this may not be the best for me

1. Automatic release to Github Release requires `Github Personal Token` and I don't have permission to get it.

2. Install Github App without permission

**Comment by TranquilMarmot** [comment]
Thanks for the explanation! Feel free to close this issue or leave it open, up to you.

(Also, for what it's worth, this fork of the extension does fix a few bugs I was encountering with the other one, such as https://github.com/justjavac/vscode-deno/issues/62 )
