### ISSUE TITLE
No types information if X-Typescript-Types is a redirect

### ISSUE THREAD

**Issue by shian15810** [axetroy/vscode-deno#147]
Same issue as https://github.com/axetroy/vscode-deno/issues/27, but this time is for typescript types if the returned `X-Typescript-Types` url is a redirect.

**Comment by axetroy** [comment]
Can you give an example code?

**Comment by shian15810** [comment]
```typescript
import wretch from "https://cdn.pika.dev/wretch"
```

**Comment by shian15810** [comment]
https://github.com/axetroy/vscode-deno/blob/ffdf7ffb0913c9711d73b467f95df2f53bc0ac46/core/module_resolver.ts#L115-L121

`typeModule.filepath` is pointing to an empty d.ts file.

**Comment by axetroy** [comment]
confirmed.

the BUG is here

https://github.com/axetroy/vscode-deno/blob/ffdf7ffb0913c9711d73b467f95df2f53bc0ac46/core/module_resolver.ts#L110-L121

https://github.com/axetroy/vscode-deno/blob/ffdf7ffb0913c9711d73b467f95df2f53bc0ac46/core/module_resolver.ts#L173-L184

https://github.com/axetroy/vscode-deno/blob/ffdf7ffb0913c9711d73b467f95df2f53bc0ac46/core/deno_cache.ts#L65-L84

Missing handling of redirection and `x-typescript-types` in `deno_cache.ts`

**Comment by axetroy** [comment]
fixed in v3.6.1

![1](https://user-images.githubusercontent.com/9758711/79545406-34bcfc00-80c3-11ea-9f3b-1187ac236ee3.gif)

**Comment by shian15810** [comment]
Wow this is incredible work! I was modifying the source code but to no avail.
