### ISSUE TITLE
An import path cannot end with a '.ts' extension. Consider importing 'https://deno.land/x/abc/mod' instead. 

### ISSUE THREAD

**Issue by slim-hmidi** [axetroy/vscode-deno#166]
### test

**Describe the bug**
I installed the plugin and I whenever I import a file from deno, I got the tslint error.

**Expected behavior**
No error displayed when import file from deno.

**Screenshots**

![deno](https://user-images.githubusercontent.com/31925861/80802978-369db980-8bb1-11ea-8282-5f04a2ea70b8.JPG)

**Versions**

vscode: 1.44.2
deno: 0.41.0
extension: 1.8.0

**Comment by axetroy** [comment]
tslint's errors are outside the scope of this extended responsibility

**Comment by Seanmclem** [comment]
@axetroy I get this error but I am not using TS Lint. Also, the gif in the extension description specifically shows, first, that this error does not appear. So it seems like this is not an issue with TS Lint, but with a basic and implied functionality desired by many

**Comment by slim-hmidi** [comment]
@axetroy I'm not using tslint and I got this error.

**Comment by Seanmclem** [comment]
@slim-hmidi For me it turned out because I needed a folder called ".vscode" in my project, with a settings.json file in it that enables the deno settings. See here: https://marketplace.visualstudio.com/items?itemName=axetroy.vscode-deno#usage

after making sure I had `"deno.enable": true`  the extension worked.
