### ISSUE TITLE
discuss: remove `deno.enable` and `deno.disable` command

### ISSUE THREAD

**Issue by axetroy** [axetroy/vscode-deno#24]
We no longer use these two commands

I think it's superfluous

If you need to enable Deno in your project

Please add in `.vscode/setting.json`

```json5
{
   "deno.enable": true
}
```

I would love to hear from the community

**Comment by brandonkal** [comment]
It can be removed as there are extensions that enable toggling settings.

**Comment by David-Else** [comment]
At the moment there is no way to automatically tell if a TS/JS project is actually a deno project, so we need a way to turn the deno extension on and off for deno/other projects.

I am not sure what the benefit of removing these `enable/disable` commands is? If I want to toggle the extension on and off I use these commands. If they are unused they are not visible on the screen or affecting any other function. @brandonkal I don't want to install any other extensions to toggle, I find it quite hard to cut back on the endless extensions that seem to jostle for my time and attention. Each one requires mental space. Why not toggle deno using the current `enable/disable`  settings?

Is there some other issue I am not considering here? If I want to enable the deno extension at the moment I simply press F1 and select `deno: Enable Deno`. The `settings.json` in my project is automatically updated. Otherwise I have to do it manually, how is that better?

Would love to hear the thinking behind this decision, maybe I am wrong, I could be persuaded! Cheers.

**Comment by brandonkal** [comment]
Toggling settings is already a solved problem i.e. https://marketplace.visualstudio.com/items?itemName=edb.settings-on-fire

is one such example. It is unnecessary and sluggish for several extensions to reimplement something.

And a note: You can easily build an extension pack or use settings sync if you find managing extensions difficult. I much prefer programs that do one thing and do it well. This is one example of something this extension doesn't need. Especially when there are better existing options for toggling.

**Comment by David-Else** [comment]
@brandonkal I had a look at that extension, check out the changelog :(

**Comment by David-Else** [comment]
@brandonkal I agree with the Unix do one thing well philosophy, I wish VS Code had toggle built in, I have been looking for a decent extension to do that for a while. I tried one before but it let me down.

I had a look at that extension you linked me, source code looked OK, but look at the changelog :(

https://github.com/ericbiewener/vscode-settings-on-fire/blob/master/CHANGELOG.md

I am old school in dependencies, I investigate them before letting them in. The pain adopting the wrong dependency will be wasted time and frustration in the future. @axetroy knows what he is doing, I had a look at his track record on Github :)

`toggle` is top rated, but last updated 3 years ago. VS Code API's change a lot in that time, it is probably total cruft... but I really don't have the time to look into it.

https://marketplace.visualstudio.com/items?itemName=rebornix.toggle

Have a look at the recent v2 update of VS Code ESLint, Dirk Baeumer added an `enable/disable` toggle! (I remember I had to install a crappy toggle extension to do that in the past, I was overjoyed to see it added :)

**Comment by brandonkal** [comment]
Yeah I haven't installed that extension...
My main point is there are many options there. According to the repo it is brand new. I've used Toggle (the popular one) so I couldn't point to that one (it wasn't amazing).
I don't buy the pain argument. It's just a browser after all. "install" and if it doesn't work out remove it or fork it.

VSCode itself is some 50 extensions so I don't mind having 100. Especially when they are small and focused ones. As they should be. My 2c.

**Comment by David-Else** [comment]
I have been playing about with the latest version of the extension. Now that the `settings.json` is becoming more vital with `"deno.import_map"` I will concede that having a toggle option is not so important.
