### ISSUE TITLE
Doing too much

### ISSUE THREAD

**Issue by brandonkal** [axetroy/vscode-deno#33]
I'm now seeing this:
```
We recommend you use a locked std version.
```
I appreciate the work that is being done here.

I thought this was a tool to fix VSCode not resolving Deno imports. Now it is trying to be a linter. Frankly, not locking imports is useful in development or when writing a Deno script for one-off tasks. This really should be the realm of  a tool like ESLint.

**Comment by axetroy** [comment]
Makes sense, I'm thinking about it

But use eslint/tslint in Deno project always make me feels weird

Introducing `package.json` and` node_modules` in the Deno project is a bad idea.

A single `.eslintrc` does not meet the conditions of lint and requires additional plugins to be loaded

**Comment by brandonkal** [comment]
Yes it is weird. With Yarn v2 we can do away with node_modules which I love.

package.json is weird but in the end we are going to have something like it.

I have some ideas on how to make this better and more "Deno-like".

Medium term it doesn't make sense to ignore the eslint ecosystem. Or even to build a parallel ecosystem (running different tools on front end JS and back-end Deno JS).

**Comment by David-Else** [comment]
I have no idea how anyone could write any JS/TS without a linter! There are so many inconsistencies and silly little rules due to legacy baggage it would be insane to try and memorize them all.

I hope there will be an eslint-deno ruleset coming along before too long. I think that would be the place for linting, so I have to agree with @brandonkal

**Comment by axetroy** [comment]
The rules have been removed

**Comment by axetroy** [comment]
I found that many people have initiated issues because the std version is not locked.

Prior to this, we supported code diagnostics and recommended users to use locked std versions

since this seems to out of scope of the extension

Now I have to reconsider this issue and should add it back

waiting the release of `@eslint/deno`, then remove it again

**Comment by axetroy** [comment]
Close the issue because Deno will land `deno lint`. ref https://github.com/denoland/deno_lint
