### ISSUE TITLE
feat: support external type definitions

### ISSUE THREAD

**Issue by axetroy** [axetroy/vscode-deno#35]
https://deno.land/std/manual.md#triple-slash-reference-directive-in-javascript-files

1. ~Compiler hint~

```ts
// @deno-types="./foo.d.ts"
import * as foo from "./foo.js";
```

2. Triple-slash reference directive in JavaScript files

```ts
/// <reference types="./foo.d.ts" />
export const foo = "foo";
```

3. X-TypeScript-Types custom header

**Comment by axetroy** [comment]
missing real example for this

**Comment by axetroy** [comment]
It looks like this feature is not very stable

Deferred for later processing

**Comment by axetroy** [comment]
already support `Triple-slash reference directive in JavaScript files`

```ts
/// <reference types="https://raw.githubusercontent.com/date-fns/date-fns/master/typings.d.ts" />

/// <reference types="./foo.d.ts" />

console.log(Foo.Example)
```

![1](https://user-images.githubusercontent.com/9758711/74108551-765a9380-4bb6-11ea-9326-f293b4756575.gif)

**Comment by axetroy** [comment]
about `@deno-types` ref: https://github.com/denoland/deno/issues/3949

My suggestion is to deprecated this parsing

**Comment by tmueller** [comment]
Hi @axetroy,

thanks for providing such a great vscode extension. :)

PikaCDN just introduced support for the `X-TypeScript-Types` custom header. You can read about it here: https://dev.to/pika/introducing-pika-cdn-deno-p8b. 
Maybe fp-ts can be used as real example for testing. It can be used like shown here: https://github.com/gcanti/fp-ts/issues/1130#issuecomment-585534177

The following code compiles fine in deno, but shows an error for the generic `array.getMonoid<number>();` in vscode. The reason seems to be, that deno is able to locate the type definitons provided by https://cdn.pika.dev/fp-ts, whereas the vscode plugin uses the .js module, that is stripped of type information like generics.

```typescript
import { array } from "https://cdn.pika.dev/fp-ts";

const M = array.getMonoid<number>();
console.log("concat Array", M.concat([1, 2], [2, 3]));
```

Maybe you can have another look at supporting the `X-TypeScript-Types` custom header?

**Comment by axetroy** [comment]
Thank you for this example.

I will try to support this.

**Comment by axetroy** [comment]
The work has been completed.

Please wait for the next release & thanks for your help

![2](https://user-images.githubusercontent.com/9758711/74463278-94810600-4ecc-11ea-9898-e213178c8004.gif)

**Comment by tmueller** [comment]
Works for me. Thanks for implementing it so fast :)
