### ISSUE TITLE
Extension seemingly broken when using Deno 0.34.0

### ISSUE THREAD

**Issue by xpyxel** [axetroy/vscode-deno#67]
### Extension seemingly broken when using Deno 0.34.0

**Describe the bug**
The path resolving functionality of the extension seems to break when updating to the latest version of Deno, version 0.34.0.

**To Reproduce**

1. Download the latest version and replace the Deno executable, or reinstall deno using the command
2. Create a new folder, open the folder inside VSCode, and set up the `.vscode/settings.json` as usual.
3. Attempt to resolve anything such as `import * as fmt from "https://deno.land/std/fmt/mod.ts";` 

**Expected behavior**

The modules should resolve successfully when the module has been cached into the DENO_DIR.

**Screenshots**

![1.png](https://owo.sh/8BaxiEV.png)

**Versions**

vscode: 1.42.1
deno: 0.34.0
extension: 2.0.4

**Comment by lucacasonato** [comment]
This is not windows only, this is because of the refactor of the file_fetcher in deno and the corresponding change in how DENO_DIR works. Instead of having a file with the name `deps/deno.land/std/http/file_server.ts` the file is now saved as deps/deno.land/[file name hash]. More info here: https://github.com/denoland/deno/pull/4030/files#diff-1e5b9797ee9e011688e5a5de7602c1f6

**Comment by axetroy** [comment]
@lucacasonato 
Thanks for telling me that. I will follow with this.
WIP

**Comment by axetroy** [comment]
Hi. vscode-deno@v3.0.0 have been release.

Deno v0.35.0 is supported again.

**Comment by xpyxel** [comment]
Closing this issue as it has been fixed, thanks for you and Deno's hard work on this.
